### PR TITLE
feat(subscriptions): Introduce tab navigation and Subscriptions screen

### PR DESCRIPTION
**Pull request by lutangar**
- Refactor SimilarProfiles component to be connected

### CODE REVIEW

**Comment by lutangar** [comment]
Hey guys, this PR is grouping a few related features :
- The subscriptions screen has been added, but to be accessible, the Tab navigation has also been added
- The new boxes introduce by @newick in #699 have been added to this PRs since one is supposed to appear on the subscriptions screen.

@JalilArfaoui I lost few hours trying to please Typescript, especially with typing of the SimilarProfiles, which is now a connected component to promote reusability, but this getting even harder to get the typings right. PLZ HELP!

@newick since I added the tab navigation, the layout is a bit off, I'll need your help to get it back on track.

**Comment by JalilArfaoui** [comment]
Let me look into in …

**Comment by JalilArfaoui** [comment]
@lutangar I’ve fixed typings issues. TypeScript was generally right … the main inconsistency being the type of `subscribe` :  declared as `(id: ContributorId) => () => void;` but used as `(id: ContributorId) => void;`

Tell me if you see anything incorrect

**Pull request merged**
