### PR TITLE
feat: redirect path from /en/* to /eclaireurs  #852

### LINKED ISSUE #852: Make the contributors js app works with english version of the website
**Describe the feature/improvement**
- 1srt and urgent : The contributors js app must be displayed on the URL https://www.dismoi.io/en/guides/
- 2nd : We must thinks about the contributor's profile pages translation strategy and release it.

**Target user**
The website visitors

### PR DESCRIPTION
**Pull request by gregoirelacoste**
point 1 de #852 
Redirect all profiles trafic from /en to /eclaireurs

### CODE REVIEW

**Review by christpet — APPROVED** [review]
Looks great, good solution!

**Comment by lutangar** [comment]
> Looks great, good solution!

I'm not sure you were the best reviewer for the job and it might have been hastily merged :sweat_smile: 

It seems #852 has been reopened by @antoinewolff 

I supposed this was a urgent fix so nevermind but please @gregoirelacoste at least mention this as a `quickfix` (or at least `fix: something`) somewhere in the commit message, so we're able to revert it once it's not needed anymore.

**Comment by gregoirelacoste** [comment]
@lutangar  yes it was just a quick fix that's why we didn't want to close the issue, i will add a mention like `quickfix` the next time. thx

**Pull request merged**
