### PR TITLE
Chore/profiles/explaining video

### PR DESCRIPTION
**Pull request by newick**
We'd like to find a way to explain DisMoi directly from the profile page.

First try with a modale opening the explaining video

linked to #922

### CODE REVIEW

**Comment by newick** [comment]
@gregoirelacoste I created the modale and the button but i don't know ho to link them :)

PS: if we could have a complete (button + modale) component, it'd be great!

**Comment by gregoirelacoste** [comment]
@newick you just have to pull, tell me if it's ok for you

**Comment by newick** [comment]
@gregoirelacoste you didn't push anything 😆

**Comment by newick** [comment]
image
@MaartenLMEM as we discussed for the sidebar.

**Comment by MaartenLMEM** [comment]
j'ai cliqué sur ready to review @newick sans le vouloir (je voulais juste revie ^^)
Moi ça me parait bien, je vais le montrer à d'autres cet aprem

**Comment by MaartenLMEM** [comment]
Vu avec Karène : juste pour le bouton player mettre un label simple du type "Comment ça marche ?" 
En effet le mot Dismoi apparait déjà 3 fois au dessus dont le titre.

**Comment by newick** [comment]
@MaartenLMEM I changed the label. 
and added the french translation. 

image
Maybe we could remove or remplace some "DisMoi" in this case, 3 times looks a lot to me.

**Comment by MaartenLMEM** [comment]
Proposition :
```
**C'est quoi DisMoi ?**
DisMoi est le 1er réseau social qui vous accompagne sur le web : recevez les conseils et éclairages de vos contributeurs de confiance directement sur les pages web que vous visitez.
```

**Comment by lutangar** [comment]
Since #900 was merged there are conflicts on your branch, you'll need to `rebase` on master, `yarn install` and run `yarn prettier`.

**Review by lutangar — APPROVED** [review]

**Comment by MaartenLMEM** [comment]
@newick voici ce que j'ai sur chrome sans l'extension quand je vais sur https://staging-profiles.dismoi.io/eclaireurs/55/CaptainFact.io

Le 1er rectangle de la colonne de droite est en doublon.

image

**Pull request merged**
