### PR TITLE
update Storybook 

### PR DESCRIPTION
**Pull request by newick**
linked to #862

### CODE REVIEW

**Comment by newick** [comment]
Finally could we just merge this one to use a proper version of Storybook now on?

**Comment by lutangar** [comment]
Sorry @newick [Semaphore](https://semaphoreci.com/dismoi/extension/branches/chore-updatestorybook/builds/1) disagree because production build is failing... requires more sweat than expected ;)

**Comment by newick** [comment]
> This build was waiting for 16:45:03, because your plan's capacity was exhausted.
What can I do about that @lutangar?

**Comment by lutangar** [comment]
I didn't see that, but this:

```
yarn build:production
```

```
ERROR in /home/runner/Extension/node_modules/@storybook/react/dist/client/preview/types.d.ts
undefined error in /home/runner/Extension/node_modules/@storybook/react/dist/client/preview/types.d.ts(2,10):
undefined  TS2305

    1 | import { ReactElement } from 'react';
  > 2 | export { RenderContext } from '@storybook/client-api';
      |          ^
    3 | export { StoryContext } from '@storybook/addons';
    4 | export interface ShowErrorArgs {
    5 |     title: string;
    ```

**Comment by newick** [comment]
@lutangar what's the difference between Semaphore and local build?
I did the `yarn build:production` and it works only with warnings.

**Comment by newick** [comment]
@gregoirelacoste @JalilArfaoui any idea to unblock the situation?

**Comment by gregoirelacoste** [comment]
@newick i have this error : TS2305: Module '"../../../../client-api/dist"' has no exported member 'RenderContext'.
on export { RenderContext } from '@storybook/client-api';

I think migration is bit more complicated than expected. 
Need to read the migration guide (https://storybook.js.org/blog/storybook-6-migration-guide/), and be carefull with typescript: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript 

> Storybook has built-in Typescript support in 6.0. That means you should remove your complex Typescript configurations from your .storybook config

**Review by christpet — APPROVED** [review]

**Comment by newick** [comment]
@gregoirelacoste could you look after this one?
I tried for nearly one hour to do something and it's more broken than before 😞

**Comment by gregoirelacoste** [comment]
I updated to the latest version 6.2.2 with the migration guide: https://storybook.js.org/blog/storybook-6-migration-guide/
So I had to update all the stories components via the CLI to switch to CSF format: https://storybook.js.org/blog/component-story-format/
The docs of the new format: https://storybook.js.org/docs/react/writing-stories/introduction || https://storybook.js.org/docs/react/api/csf
It's much better by the way;)

I had a bunch of Chokidar errors, I passed the check typescript to false while waiting to find a better solution

**Review by gregoirelacoste — APPROVED** [review]

**Comment by newick** [comment]
@gregoirelacoste LGTM.
There's still some `storiesOf`, do you need help to clean it?

**Pull request merged**
