### PR TITLE
fix(NoticesList): way to display more than 2 notices

### LINKED ISSUE #850: If there are more than 2 notices on a page, they are invisible
**Describe the feature/improvement**
Let see that there are more than 2 notices on a same page and give access to them

**Target user**
DisMoi addon users

**Fill in the following areas if you have the time...**

**User stories**
How will the user experience this feature/improvement?
1. The visit a page where there a 3 (or more) notices matching
2. User can see the two first preview, and I can see that there are others 

**Technical implementation notes**
Display all bubbles and add a scrollbar

**Additional context**
It s also an issue for a contributor whose contributions are invisible, which is frustrating (got a mail about this case (see [this page](https://www.sephora.fr/shop/soin-visage/demaquillant-et-nettoyant-c7633/)) from Ethik'do wher bubble 1524 is not visible.
image

### PR DESCRIPTION
**Pull request by newick**
A way to fix #850

@MaartenLMEM / @christpet visually it would be something like 
image

@gregoirelacoste could you find a way to hide the message if there's less than 2 notices?

### CODE REVIEW

**Comment by MaartenLMEM** [comment]
**Wording** : use `contributions` instead of bulles, which is more internal.
**Display** : Is it possible to show the 1st head of the third notice instead of this "there is more" line ?
Because currenly, button "Poster" collide with any label right above.

**Comment by newick** [comment]
@MaartenLMEM something like this?

image

**Comment by MaartenLMEM** [comment]
I prefer this direction yes, seems me more clear. What do you think @christpet ?

Oh ! Actuallly what about puting the button "Poster" after the last bubble into the scroll area ? Isn't it more consistent with for contribution process on this screen (I read what is written here and I add something if I want) ?

**Comment by newick** [comment]
> Oh ! Actuallly what about puting the button "Poster" after the last bubble into the scroll area ? Isn't it more consistent with for contribution process on this screen (I read what is written here and I add something if I want) ?

Depends of what we want.
If it's to get contributions, the button should be displayed all the time.
If we want Users to be sure that they won't publish duplicate content, the button could be in the scrollbar. 

I think the last solution works only if the Users can share a contribution.

@prk-dismoi, do you have any idea about that?

**Comment by gregoirelacoste** [comment]
>  the button "Poster" after the last bubble into the scroll area ?
It might be discouraging to scroll to post if there is too much content ?
@newick what can i do to help you on it ?

**Comment by christpet** [comment]
> @christpet so without number of contributions ? even with something like this ?
> image

Good thinking, but I'm not sure there's a clear need for that yet. I always try to operate with the principle of removing as much as possible from the interface unless it's necessary. We can add it later if needed!

**Comment by gregoirelacoste** [comment]
> I always try to operate with the principle of removing as much as possible from the interface unless it's necessary

ok !

**Comment by gregoirelacoste** [comment]
result for last push: 
image

**Comment by MaartenLMEM** [comment]
ok for our contribution partners, I think for users also :)

**Comment by gregoirelacoste** [comment]
> ok for our contribution partners, I think for users also :)

- if we favor users > no visible "post" button
- if we favor contributor > visible "post" button
- 
who to favor?

**Comment by MaartenLMEM** [comment]
@christpet choosed "post button" - Follow him !
(By the way I agree because it is the most simple)

**Comment by newick** [comment]
@gregoirelacoste give me 15min to try the box shadow

**Comment by newick** [comment]
first try is ugly 
image

I try something else

**Comment by christpet** [comment]
@newick almost there - make the shadow go the other direction!

**Comment by newick** [comment]
@christpet not sure it helps 
image

**Comment by gregoirelacoste** [comment]
> @christpet not sure it helps
> image

would that be fine to add a wrapper to "poster" button (100%width) and  give a box shadow only on top ?

**Comment by newick** [comment]
good idea @gregoirelacoste 
image

**Comment by newick** [comment]
@gregoirelacoste is there a way to use a prop to display the box-shadow only for more than 2 contribs?

**Comment by gregoirelacoste** [comment]
@newick yes, i do that at 2pm if you want

**Comment by christpet** [comment]
@newick @gregoirelacoste looks great. Yes if you can do that quickly at 2pm then let's ship it!

**Comment by gregoirelacoste** [comment]
last push : 
for 3 and more contributions
image

for less
image

**Review by christpet — APPROVED** [review]
Excellent work @gregoirelacoste and @newick ! Looks great to me. This looks like it is good to go. Shall we merge?

**Comment by gregoirelacoste** [comment]
@christpet i do

**Pull request merged**
