### PR TITLE
feat(i18n): add i18next

### LINKED ISSUE #799: Choose i18n library (English Version)

### PR DESCRIPTION
**Pull request by gregoirelacoste**
closes #799

### CODE REVIEW

**Review by lutangar — APPROVED** [review]
:tada:

**Comment by lutangar** [comment]
Woops merged it too fast :sweat_smile:

**Comment by gregoirelacoste** [comment]
@lutangar hi, woops, so i create an new branch ? With same name ?

**Comment by lutangar** [comment]
I removed distant branch. You can stay on this branch, just push it back here and create a new PR.

**Pull request merged**
