### PR TITLE
Feat/no notice screen update

### PR DESCRIPTION
**Pull request by newick**
@lutangar I need a bit of help for the background.
Maybe could you storify it?

### CODE REVIEW

**Comment by lutangar** [comment]
@newick 
1. The background looks fine (grey) in the question funnel. Where did you want that grey background?
2. I implemented the choice of the contributor on the question form. Is there anything left to implement?

If @JalilArfaoui want to review this feature now is the time :p

**Review by lutangar — APPROVED** [review]

**Comment by MaartenLMEM** [comment]
@newick I don't know precisely what space on screen it s about, but use "source" or "source d’information" instead of 'informateur" plz

**Comment by lutangar** [comment]
> Can we have a default text like "Choix de l'informateur"

There is an empty option in `<RadiosFilters />`  you can the label there.

**Comment by newick** [comment]
@lutangar there is no `<select>` in `<RadioFilters />` 🤔

**Comment by lutangar** [comment]
@newick sorry, look at `QuestionForm`
There is an empty `option` there, you can put anything there.

**Comment by newick** [comment]
Good for me

**Pull request merged**
