### PR TITLE
Storybook/reorder

### PR DESCRIPTION
**Pull request by newick**
Tried to improve readibilty, to discuss 🗣️ 

Viewable live at https://storybook.lmem.net/reorder

### CODE REVIEW

**Comment by JalilArfaoui** [comment]
Shouldn’t we have 
- `/screens` in `/Extension` ?
- `/organisms` in `/Components/Organisms` ?

**Comment by JalilArfaoui** [comment]
I’ve added a Storybook deployment for this branch : https://storybook.lmem.net/reorder/

**Comment by newick** [comment]
@JalilArfaoui @lutangar I'm ok with it now. 
Could you review it before merging?

**Comment by lutangar** [comment]
@newick looks good, just going to rewrite history a bit (remove merge commit)

**Pull request merged**
