### PR TITLE
chore(profilesonboarding): configure webpack for video assets

### LINKED ISSUE #1006: Load video on Onboarding Prod
Load video mp4 inside js bundle
use Webpack chunk and React Lazy

### PR DESCRIPTION
**Pull request by gregoirelacoste**
@JalilArfaoui i pushed with --no-verify
could you check and tell me if it's ok please thx
closes #1006

### CODE REVIEW

**Comment by lutangar** [comment]
Since #900 was merged there conflicts appeared on your branch, you'll need to `rebase` on master, `yarn install` and run `yarn prettier`.

**Comment by gregoirelacoste** [comment]
> Since #900 was merged there conflicts appeared on your branch, you'll need to `rebase` on master, `yarn install` and run `yarn prettier`.

I did yarn install && yarn prettier. I still have issue on yarn build:storybook on my branch but not in master even after rebase. do you have an idea why ? @lutangar

**Comment by lutangar** [comment]
I'm going to check this out.

**Comment by lutangar** [comment]
```
yarn storybook
ERROR in ./src/assets/video/dismoi-onboarding.mp4 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./src/app/profiles/App/OnBoarding/Steps/Step2.tsx 7:0-54 41:9-13
 @ ./src/app/profiles/App/OnBoarding/Steps/index.ts
 @ ./src/app/profiles/App/OnBoarding/index.tsx
 @ ./src/app/profiles/App/OnBoarding/OnBoarding.stories.tsx
 @ ./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.tsx)$
 @ ./.storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-server/dist/cjs/globals/polyfills.js ./node_modules/@storybook/core-server/dist/cjs/globals/globals.js ./.storybook/storybook-init-framework-entry.js ./.storybook/preview.tsx-generated-config-entry.js ./.storybook/generated-stories-entry.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```

I suppose this has to do with your loader config.

**Comment by gregoirelacoste** [comment]
@lutangar I did ` {
          test: /\.(mp4)$/i,
          include: path.resolve(__dirname, 'src/'),
          loader: 'file-loader',
          options: {
            outputPath: 'video',
            publicPath: 'https://profiles.dismoi.io/video/',
            name: '[path][name].[ext]',
            context: 'src/assets/video'
          }`

**Comment by lutangar** [comment]
I added 7e99bc6 this might be sufficient but the video path might not be what you are expected tho.
You might give this another look. It  also might help you simplify your webpack rule dependending on your needs.

**Pull request merged**
