### PR TITLE
fix: PROFILES_ORIGIN must be base url

### PR DESCRIPTION
**Pull request by JalilArfaoui**

### CODE REVIEW

**Review by lutangar — APPROVED** [review]
:+1: I think it's used for CORS somewhere

**Comment by JalilArfaoui** [comment]
@lutangar and it’s use to open the right options page … and my fix for https://github.com/dis-moi/extension/issues/1178 was not good enough 😅

**Comment by prk-dismoi** [comment]
Hey @JalilArfaoui can I move this one to "Ready for prod"?

**Comment by JalilArfaoui** [comment]
Yes

**Pull request merged**
