### PR TITLE
Fix/onboarding feedbacks

### PR DESCRIPTION
**Pull request by newick**
⚠️ i did `git push --no-verify` cause of errors.

When errors are solved, it can go to staging cc @MaartenLMEM

### CODE REVIEW

**Review by gregoirelacoste — COMMENTED** [review]
LGTM, I see no error what message do you have with git push ? could you copy paste here ?

**Comment by gregoirelacoste** [comment]
you also need to edit translation before merge : `src/i18n/resources/en/profiles.json `

**Comment by newick** [comment]
```
husky > pre-push (node v15.11.0)
yarn run v1.22.10
$ yarn test && yarn typecheck && yarn lint && yarn build:chromium:production && yarn build-storybook
$ BACKEND_ORIGIN='' mocha -r ts-node/register -r tsconfig-paths/register -r jsdom-global/register 'src/**/*.spec.ts' 'test/app/*.ts' 'test/app/**/*.ts'


  prefsReducer reducer
    ✓ dismiss notice
    ✓ like notice
    ✓ dislike notice
    ✓ undismiss notice
    ✓ unlike notice
    ✓ undislike notice
    ✓ read notice

  background > reducers > resources
    ✓ initial state + receivedMatchingContexts => state with offers

  background > reducers > serviceMessage
    ✓ saves the lastShownDate when OPENED from a service message action

  background > reducers > subscriptions
    ✓ is empty initially
    ✓ saves subscriptions
    ✓ saves unsubscriptions

  background > reducers > tabs
    when receiving NAVIGATED_TO_URL
      ✓ saves new or updated tab info
      ✓ keeps existing tab info when receiving NAVIGATED_TO_URL

  background selectors
    onboarding selectors
      isInstallationComplete
        ✓ can tell if the installation is complete whatever the install reason was
      isOnboardingRequired
        ✓ should return false when the user has accepted TOS

  background > selectors > serviceMessage
    getServiceMessageLastShowDate
      ✓ returns the message's last date

  background > selectors > subscriptions
    getContributorsWithSubscriptionState
      ✓ returns contributors list with subscription status
    getNbSubscriptions
      ✓ returns the number of subscriptions

  background > selectors > tabs
    getTabsList
      ✓ returns all known tabs an an array
    getReadyTabs
      ✓ returns all tabs that are marked ready
    getOptionsTabs
      ✓ returns all options tabs

  migrations/4
    if previous state has `readNotices` key
      ✓ removes the `readNotices` keys
      ✓ keeps old `readNotices` data in `markedReadNotices` key
    if previous state doesn't have `readNotices` key
      ✓ does nothing (120ms)

  migrations/5
    if previous state has `markedReadNotices` key
      ✓ removes the `readNotices` keys
      ✓ keeps old `markedReadNotices` data in `readNotices` key
    if previous state doesn't have `markedReadNotices` key
      ✓ does nothing

  content > reducers > serviceMessage
    ✓ initialize to []
    ✓ shows update message when receive SERVICE_MESSAGE
    ✓ removes the update message when UI is CLOSED

  content > reducers > openReducer
    ✓ has initial state all false
    mounted state
      ✓ becomes true when OPENED
      ✓ stays true on CLOSED
    open state
      ✓ becomes true when OPENED
      ✓ becomes false when CLOSED
    loaded state
      ✓ stays false when OPENED
      ✓ becomes true when LOADED
      ✓ becomes false when CLOSED
      ✓ stays false LOADED but already closed

  content > selectors > serviceMessage
    serviceMessage
      ✓ returns false if there is no serviceMessage
      ✓ returns true if serviceMessage is true

  content > selectors > ui
    getTitle
      ✓ returns notification title
    isMounted
      ✓ returns true if app is mounted
    isOpen
      ✓ returns true if app has finished (fake) loading
    isLoaded
      ✓ returns true if app has finished (fake) loading

  lmem/contribution/validate
    ✓ rejects undefined contribution
    ✓ rejects empty contribution
    ✓ rejects contribution missing message
    ✓ rejects contribution missing contributor
    ✓ rejects contribution missing contributor name
    ✓ rejects contribution missing contributor email
    ✓ rejects contribution with invalid contributor email
    ✓ sums up all the error messages
    ✓ returns empty object for valid contribution

  lmem > contributor
     contributorIsSubscribed
      ✓ returns true if we're subscribed to it
      ✓ returns false if we're subscribed to it
      ✓ returns false if we don't know
    findContributorIn
      ✓ finds contributor when present in list (64ms)
      ✓ returns null when contributor not present in list

  lmem > notice
    incrementRating
      ✓ return the rating plus one
      ✓ return 1 even if rating is not defined
    decrementRating
      ✓ return the rating minus one
      ✓ return 0 even if rating is not defined

  lmem > tab
    isOptionsTab
      ✓ returns true if given tab is an options tab
      ✓ returns false if given another kind of tab
      ✓ returns false if given null or undefined

  isAction
    ✓ return true if the action got a type
    ✓ return false for an empty object

  isAction
    ✓ return false if the action got an extra prop
    ✓ return true for a fully features standard action
    ✓ return true for an error action

  options > reducers > contributors
    ✓ is empty initially
    ✓ saves contributors

  options > selectors > contributors
    getNbTotalContributors
      ✓ returns number of total contributors
    getContributorsSortedByContributions
      ✓ returns contributors state, sorted by nb of contributors
    getSubscriptions
      ✓ returns subscribed contributors
    getContributorsSuggestions
      ✓ returns contributors sorted by contributions
    makeGetNContributorsSuggestions
      with limit higher than available suggestions
        ✓ returns a selector for all the suggestions
      with limit lower than available suggestions
        ✓ returns a selector for first N suggestions

  stripFormMeta
    ✓ remove resolve and reject meta

  areWithinHours
    ✓ returns true if the first date is within the last 4 hours of the second date
    ✓ returns true if the first date is before the second date
    ✓ returns false if the second date is past the last 4 hours of the first date
    ✓ returns false if the second date is past the 4 hours and 1 second of the first date

  Get message with youtube player
    ✓ should return player html with url with no anchor and text

  uniqId
    ✓ always return 16 chars
    ✓ generate sufficiently uniq ids

  background actions
    ✓ receivedMatchingContexts
    ✓ contextTriggered (58ms)
    ✓ noticeDisplayed
    ✓ noticeIgnored when notice dismissed
    ✓ noticeIgnored when notice disliked

  content actions
    ✓ init
    ✓ noticesFound
    ✓ dismiss notice (66ms)
    ✓ likes notice

  isHtmlElementInteractive
    ✓ can tell if actual Html elements are interactive (118ms)

  filterContextsMatchingUrl
    ✓ should be case insensitive
    exclusion
      ✓ should exclude matching exclusion of otherwise matching url
      ✓ should not exclude non matching exclusion of matching url
[ERROR] CatchedError: Invalid regular expression: /isNasty)/: Unmatched ')'
      ✓ should exclude its matching context if regex is invalid
    invalid regex
      ✓ should not screw up the matching engine
    empty prefs
      ✓ should match when the url matches an offer
      ✓ should not match when the url does not match any offer

  isNoticeValid
    ✓ Object with missing contributor is not valid
    ✓ Object with missing message is not valid
    ✓ Object with all props is valid
    ✓ Object with all props but optional is valid

  createMessageHandler
    ✓ emits INVALID_ACTION if received an invalid action
    ✓ emits the valid action with meta.from content added (59ms)
    ✓ emits the valid action with meta.from options added

  isEmail
    ✓ returns false if falsy
    ✓ returns false for "some words"
    ✓ returns false for "http://some.site"
    ✓ returns false for "some @email.com"
    ✓ returns true for "some@email.com"
    ✓ returns true for "s@e.co"

  truncateWords
    ✓ does nothing on empty string (99ms)
    ✓ does nothing if less words than limit
    ✓ does nothing if as many words as limit
    ✓ does truncate if more words than limit
    ✓ is currified
    ✓ is composable


  124 passing (1s)

$ tsc --noEmit
$ yarn lint:ts
$ eslint "./src/**/*.{js,ts}"
$ NODE_ENV=production yarn build:chromium
$ webpack --mode=production --env.PLATFORM=chromium
Building package to:  /Users/dev/Boulot/DisMoi/extension/build/production/chromium
./production/chromium.js
Starting type checking service...
Connection to github.com closed by remote host.
Time: 197496ms
Environment (--env): {
  "PLATFORM": "chromium"
}
                                  Asset       Size  Chunks                   Chunk Names
         ../bulles-v3.73.2-chromium.zip   3.23 MiB          [emitted]
                              .DS_Store     10 KiB          [emitted]
                        background.html  158 bytes          [emitted]
                      browserconfig.xml  250 bytes          [emitted]
                            favicon.ico   14.7 KiB          [emitted]
                        fonts/.DS_Store      6 KiB          [emitted]
             fonts/LatoLatin-Heavy.woff   70.6 KiB          [emitted]
            fonts/LatoLatin-Heavy.woff2   43.2 KiB          [emitted]
       fonts/LatoLatin-HeavyItalic.woff   71.5 KiB          [emitted]
      fonts/LatoLatin-HeavyItalic.woff2   44.7 KiB          [emitted]
            fonts/LatoLatin-Medium.woff   70.3 KiB          [emitted]
           fonts/LatoLatin-Medium.woff2   42.9 KiB          [emitted]
      fonts/LatoLatin-MediumItalic.woff   71.4 KiB          [emitted]
     fonts/LatoLatin-MediumItalic.woff2   43.9 KiB          [emitted]
          fonts/LatoLatin-Semibold.woff   71.4 KiB          [emitted]
         fonts/LatoLatin-Semibold.woff2   43.3 KiB          [emitted]
    fonts/LatoLatin-SemiboldItalic.woff   72.8 KiB          [emitted]
   fonts/LatoLatin-SemiboldItalic.woff2   44.3 KiB          [emitted]
              fonts/lato-latin-100.woff   26.2 KiB          [emitted]
             fonts/lato-latin-100.woff2   20.9 KiB          [emitted]
        fonts/lato-latin-100italic.woff   21.3 KiB          [emitted]
       fonts/lato-latin-100italic.woff2   16.6 KiB          [emitted]
              fonts/lato-latin-300.woff   29.2 KiB          [emitted]
             fonts/lato-latin-300.woff2   22.7 KiB          [emitted]
        fonts/lato-latin-300italic.woff   21.8 KiB          [emitted]
       fonts/lato-latin-300italic.woff2   17.1 KiB          [emitted]
              fonts/lato-latin-400.woff   27.7 KiB          [emitted]
             fonts/lato-latin-400.woff2   22.8 KiB          [emitted]
        fonts/lato-latin-400italic.woff   28.9 KiB          [emitted]
       fonts/lato-latin-400italic.woff2   23.6 KiB          [emitted]
              fonts/lato-latin-700.woff   27.2 KiB          [emitted]
             fonts/lato-latin-700.woff2   22.3 KiB          [emitted]
        fonts/lato-latin-700italic.woff     29 KiB          [emitted]
       fonts/lato-latin-700italic.woff2   23.7 KiB          [emitted]
              fonts/lato-latin-900.woff   26.6 KiB          [emitted]
             fonts/lato-latin-900.woff2   21.8 KiB          [emitted]
        fonts/lato-latin-900italic.woff     28 KiB          [emitted]
       fonts/lato-latin-900italic.woff2     23 KiB          [emitted]
      fonts/sedgwick-ave-latin-400.woff   38.9 KiB          [emitted]
     fonts/sedgwick-ave-latin-400.woff2   33.5 KiB          [emitted]
                          img/.DS_Store      6 KiB          [emitted]
               img/apple-touch-icon.png   7.22 KiB          [emitted]
                          img/arrow.svg  338 bytes          [emitted]
     img/contributors/logo-bordeaux.png   2.85 KiB          [emitted]
img/contributors/logo-colibri-ecolo.png   5.46 KiB          [emitted]
     img/contributors/logo-le-monde.png   3.83 KiB          [emitted]
  img/contributors/logo-les-inrocks.png   4.03 KiB          [emitted]
       img/contributors/logo-micode.png    5.6 KiB          [emitted]
  img/contributors/logo-que-choisir.png   4.31 KiB          [emitted]
                   img/logo/128x128.png   4.64 KiB          [emitted]
                     img/logo/16x16.png   1.43 KiB          [emitted]
                   img/logo/192x192.png   14.8 KiB          [emitted]
                     img/logo/32x32.png    4.2 KiB          [emitted]
                     img/logo/48x48.png   2.33 KiB          [emitted]
                   img/logo/512x512.png   28.2 KiB          [emitted]
                     img/logo/black.svg   1.54 KiB          [emitted]
              img/logo/grey/128x128.png   4.26 KiB          [emitted]
                img/logo/grey/16x16.png   1.37 KiB          [emitted]
                img/logo/grey/48x48.png   2.18 KiB          [emitted]
      img/logo/logo-lmem-background.png   2.73 KiB          [emitted]
            img/logo/logo-lmem-blue.png   8.15 KiB          [emitted]
                 img/mstile/150x150.png   6.33 KiB          [emitted]
                 img/profile-banner.jpg   26.8 KiB          [emitted]
                js/background.bundle.js    417 KiB       0  [emitted]        background
            js/background.bundle.js.map   1.88 MiB       0  [emitted] [dev]  background
                 js/browser-polyfill.js     36 KiB          [emitted]
                   js/content.bundle.js    765 KiB       1  [emitted]        content
               js/content.bundle.js.map   2.99 MiB       1  [emitted] [dev]  content
                          manifest.json    1.8 KiB          [emitted]
                       site.webmanifest  360 bytes          [emitted]
                        video/.DS_Store      6 KiB          [emitted]
            video/dismoi-onboarding.mp4    333 KiB          [emitted]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  js/background.bundle.js (417 KiB)
  js/content.bundle.js (765 KiB)
  video/dismoi-onboarding.mp4 (333 KiB)
  ../bulles-v3.73.2-chromium.zip (3.23 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  background (417 KiB)
      js/background.bundle.js
  content (765 KiB)
      js/content.bundle.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
$ build-storybook
info @storybook/react v6.2.2
info
info => Cleaning outputDir: /Users/dev/Boulot/DisMoi/extension/storybook-static
info => Loading presets
info => Compiling manager..
info => Compiling preview..
info => Loading 1 config file in "/Users/dev/Boulot/DisMoi/extension/.storybook"
info => Adding stories defined in "/Users/dev/Boulot/DisMoi/extension/.storybook/main.js"
info => Using implicit CSS loaders
(node:4068) DeprecationWarning: Relying on the implicit PostCSS loader is deprecated and will be removed in Storybook 7.0.
If you need PostCSS, include '@storybook/addon-postcss' in your '.storybook/main.js' file.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-implicit-postcss-loader for details.
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading custom Webpack config (full-control mode).
Starting type checking service...
95% emitting fork-ts-checker-webpack-plugininfo => Manager built (2.65 min)
info => Preview built (2.92 min)
WARN asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
WARN This can impact web performance.
WARN Assets:
WARN   main.91a06fba.iframe.bundle.js (541 KiB)
WARN   vendors~main.3f9d2178.iframe.bundle.js (3 MiB)
WARN entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
WARN Entrypoints:
WARN   main (3.53 MiB)
WARN       runtime~main.b0af52cf.iframe.bundle.js
WARN       vendors~main.3f9d2178.iframe.bundle.js
WARN       main.91a06fba.iframe.bundle.js
WARN
WARN webpack performance recommendations:
WARN You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
WARN For more info visit https://webpack.js.org/guides/code-splitting/
info => Output directory: /Users/dev/Boulot/DisMoi/extension/storybook-static
✨  Done in 625.26s.
```

**Comment by newick** [comment]
@gregoirelacoste if it's good for you, we can merge to staging.

**Comment by gregoirelacoste** [comment]
> @gregoirelacoste if it's good for you, we can merge to staging.

I see no bug, everything is working, so let's merge !

**Pull request merged**
