### PR TITLE
Update CONTRIBUTING.md - Firefox Staging testing

### PR DESCRIPTION
**Pull request by christpet**
Added a few lines on how to test new releases in Firefox Staging & Proding, following our conversation @lutangar

### CODE REVIEW

**Comment by lutangar** [comment]
About testing we're missing a few important points here.

You found a bug in #800 but we're missing key elements to identify the source of the bug.
I'll dig to find out what went wrong on this specific case but since you were there and discover it,
it'll save everyone times if you could join `console` elements when you're identifying a bug.

I'll update this branch with more elements, and we should probably create a dedicated `TESTING.md` file.
> we should keep in mind and put somewhere on the road "to generate a documentation website" with all these files.


## Extension architecture
Anyway about the logs, take a pick at this flow diagram illustrating the extension architecture :
> https://demo.hedgedoc.org/eI0CDEirRpWHBKgprLjS9Q

```mermaid
graph TD
    Bakground[<Extension> Background script] -->|get data from| Backend(Backend API)
    Content[<Extension> Content app] -->|get data from| Bakground
    Profiles[<Extension> Profiles app] -->|-if extension-| Bakground
    Profiles[<Extension> Profiles app] -->|-if no extension-| Backend
```

## Logs 
There are 2 important console logs to track down a bug:
- The content script console logs are available as usual from the console of the page you're currently browsing
Accessible from `ctrl+maj+i` on my OS
- The background console logs (see this as a *special page* having its own console)
This one need is a bit hidden:
1. `about:addons`
2. _debug Add-ons__
3. Click inspect

Dunno what's best, sometimes @MaartenLMEM used screenshot or video the console, but we might as well copy and paste the logs in the specific issue and use the `code` *backticks* to format these.

**Comment by christpet** [comment]
Amazing, some really good points. To push this forward: 

1. YES let's create the testing checklist! Do you want to add it all to this PR, or should we create a separate one?
2. Agreed, best to include console elements.
3. Thank you for the extension architecture diagram - super helpful. I will need some more help to understand where to find the background console logs you mentioned.

**Comment by lutangar** [comment]
Let's do that in here, I'd appreciate any help on the redaction part.
About the `background` logs, ping me, I'll help with that.

**Review by JalilArfaoui — APPROVED** [review]

**Comment by lutangar** [comment]
I think @MaartenLMEM this looks sufficiently important to be put on your todo. This document should be the way to go for anyone of the team doing some testing and how to report an issue efficiently. As we previously discussed you're the best candidate to give the finish this document.

**Review by MaartenLMEM — APPROVED** [review]

**Comment by MaartenLMEM** [comment]
I approve what i read 
But I don"t see a part of the discussion, about reporting issue. I need some context and help, to be discussed during our next meeting @lutangar

**Comment by MaartenLMEM** [comment]
Discussed with Johan : next step : I will improve templates

**Review by lutangar — APPROVED** [review]

**Pull request merged**
