### PR TITLE
fix(DetailsContent): changes margins to improve readibility

### LINKED ISSUE #742: Margin missing on detailed message when there is the scrollbar

### PR DESCRIPTION
**Pull request by newick**
fixes #742

### CODE REVIEW

**Review by JalilArfaoui — APPROVED** [review]
LGTM

**Comment by lutangar** [comment]
@newick I think the idea was to put a margin only when there is a scrollbar. Would that be possible?

**Comment by MaartenLMEM** [comment]
My bad, Erick showed me th UI without scrollbar and I didn't give this feedback. 
It's a bit quibbling but to me also it seems better to keep text so large as possible when there is no scroll bar, in this case margin can be thiner.

**Review by lutangar — APPROVED** [review]

**Pull request merged**
