### PR TITLE
refactor(extension): change labels for éclaireur

### LINKED ISSUE #804: Modifications Menu Extension
Dans le menu : 
Remplacer Abonnement par "Eclaireurs"
image

Modifier "Vous suivez X sources" par "Vous suivez X éclaireurs"
image

Bouton "Gérer mes abonnements" par "Gérer mes éclaireurs"
image

### LINKED ISSUE #806: Labels des onglet de la Page https://www.dismoi.io/sources [Quick win]
@christpet @MaartenLMEM @antoinewolff 

Pour cette page : je ne sais pas trop comment différencier le menu "Sources" et le menu "Abonnements" 
Est ce que l'on modifie Sources en "Eclaireurs du web" et on laisse "Abonnements" ou "Eclaireurs que vous suivez" qqch comme cela ?

image

### PR DESCRIPTION
**Pull request by gregoirelacoste**
closes #804 closes #806

### CODE REVIEW

**Comment by gregoirelacoste** [comment]
I changed "Abonnements" to "Eclaireurs" if you want to check  
image

**Review by lutangar — APPROVED** [review]

**Comment by gregoirelacoste** [comment]
@MaartenLMEM @christpet  hi, I changed the labels Sources / Abonnements by Tous / Suivis. 
Do you agree ?
image

**Comment by lutangar** [comment]
> This branch has conflicts that must be resolved

Could you rebase please?

**Review by christpet — APPROVED** [review]

**Review by JalilArfaoui — APPROVED** [review]

**Pull request merged**
